# Generated by Django 3.1 on 2020-09-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fairy',
            name='code',
            field=models.IntegerField(default=111111),
            preserve_default=False,
        ),
    ]
