# Generated by Django 3.1 on 2020-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairy', '0003_quest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='question',
            new_name='answer1',
        ),
        migrations.AddField(
            model_name='quest',
            name='answer2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
